### ISSUE TITLE
Python getting started docs don't work with 7.0.0 sdk

### ISSUE THREAD

**Issue by brianr** [launchdarkly/LaunchDarkly-Docs#101]
Hi LaunchDarkly team!

I followed the instructions at https://docs.launchdarkly.com/sdk/server-side/python#getting-started with a fresh Python project, and ran into the following error:

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    ldclient.set_sdk_key(LD_KEY)
AttributeError: module 'ldclient' has no attribute 'set_sdk_key'
```

**Comment by brianr** [comment]
I found a solution; is this the recommended way?

```
import ldclient
ldclient.set_config(ldclient.config.Config(sdk_key='my-sdk-key'))
```

**Comment by bwoskow-ld** [comment]
Hi @brianr, thanks for filing this. We have an [open PR](https://github.com/launchdarkly/LaunchDarkly-Docs/pull/99) for this documentation fix.

**Comment by bwoskow-ld** [comment]
The documentation has been fixed.
